
openapi: 3.0.0
info:
  title: CashBox API
  version: 1.0.0
paths:
  /cash/transactions:
    post:
      summary: Register a cash operation
      operationId: createCashTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashOperation'
      responses:
        '201':
          description: Operation accepted
        '400':
          description: Invalid request
        '500':
          description: Server error
components:
  schemas:
    CashOperation:
      type: object
      required:
        - atmId
        - type
        - amount
        - currency
        - ts
      properties:
        atmId:
          type: string
          example: ATM-MSK-001
        type:
          type: string
          enum: [CASH_IN, CASH_OUT]
          example: CASH_IN
        amount:
          type: number
          format: float
          example: 5000.00
        currency:
          type: string
          example: RUB
        ts:
          type: string
          format: date-time
          example: 2025-07-21T15:30:00Z
